export const AVATAR_SIZE = 36;
export const HOME_DOCUMENTS_PER_PAGE = 10;

export const DOC_INITIAL_LEFT_MARGIN = 56;
export const DOC_INITIAL_RIGHT_MARGIN = 56;

export const ACTIVITY_BAR_WIDTH = 48;
export const EXPLORER_SIDEBAR_DEFAULT_WIDTH = 256;
export const EXPLORER_SIDEBAR_MIN_WIDTH = 200;
export const EXPLORER_SIDEBAR_MAX_WIDTH = 400;
