export const AVATAR_SIZE = 36;
export const HOME_DOCUMENTS_PER_PAGE = 10;

export const DOC_INITIAL_LEFT_MARGIN = 56;
export const DOC_INITIAL_RIGHT_MARGIN = 56;

export const ACTIVITY_BAR_WIDTH = 48;

export const SIDEBAR_PANEL_DEFAULT_WIDTH = 350;
export const SIDEBAR_PANEL_MIN_WIDTH = 350;
export const SIDEBAR_PANEL_MAX_WIDTH = 700;
